ALTER TABLE rides ADD COLUMN IF NOT EXISTS confirmou_presenca TIMESTAMP;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS sinal_charge_id TEXT;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS sinal_pix_payload TEXT;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS sinal_estornado BOOLEAN DEFAULT false;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS disparada_at TIMESTAMP;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS alerta_30min_enviado TIMESTAMP;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS bloqueado_agendamento_ate TIMESTAMP;